name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Check EC2 status and start if stopped
      id: ec2
      run: |
        INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID }}
        
        STATE=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query "Reservations[0].Instances[0].State.Name" \
          --output text)

        echo "EC2 instance state: $STATE"

        if [ "$STATE" = "stopped" ]; then
          echo "Starting EC2 instance..."
          aws ec2 start-instances --instance-ids $INSTANCE_ID

          echo "Waiting for EC2 to be running..."
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        fi

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd FE-CI-CD-Practice
          git pull origin main
          npm install
          npm run build
          pm2 delete frontend || true
          pm2 start "serve -s dist -l 3000" --name frontend
          pm2 save